### ISSUE TITLE
Suggestion: Method names

### ISSUE THREAD

**Issue by kevinruscoe** [karlomikus/theme#1]
Just a suggestion, but Laravel's conventions are generally put(), get(), has(), all().

Would it make more sense, from a Laravel point of view, but use these names?

Theme::getThemes(); becomes Theme:all()
Theme::themeExists('theme-namespace'); becomes Theme::has('theme-namespace');

Other than that, terrific job, can't wait to use this!

**Comment by mvpoorna** [comment]
<h1><b>rwe</b></h1>
